**Notas de numpy**

En este cuaderno vamos a contar con las funciones principales que ofrece la libreria para el manejo de datos.


In [ ]:
import numpy as np
#Generamos un arreglo
print('Creamos un arreglo: ')
a = np.array([1,2,3,4,5])
print(a)

print('Podemos indicar el tipo de dato almacena un arreglo')
c=np.array([1,2,3,4,5], dtype=str)
print(c)


c=np.array([1,2,3,4,5], dtype=np.complex)
print('Números complejos: ',c )

print('Genera un arreglo con el rango 0 a rango mayor-1')
print(np.arange(0,100))



#Funciones de numpy para arreglos
print('Genera un arreglos con 0: ')
print(np.zeros(10,dtype=int))

print('Gener un arreglo con 1: ')
print(np.ones(10,dtype=int))

print('Generar con arreglo con datos basura:')
print(np.empty(10,dtype=float))

print('Generar con arreglo con datos aleatorios, los primeros 2 numeros son el rango y el 3ro la longitud:')
print(np.random.randint(0,100,10))


#Atributos del arreglo
print('Obtener el valor del arreglo')
print(a[3])

print('Editar un elemento del arreglo')
a[0]=100
print(a)

print('Cantidad de atributos que almacena')
print(a.size)

print('Obtiene la dimension del arreglo')
print(a.ndim)

print('Saber el tipo de dato que almacena')
print(a.dtype)

print('Conocer la dimension y la cantidad de elementos')
print(a.shape)




Creamos un arreglo: 
[1 2 3 4 5]
Podemos indicar el tipo de dato almacena un arreglo
['1' '2' '3' '4' '5']
Números complejos:  [1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]
Genera un arreglo con el rango 0 a rango mayor-1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Genera un arreglos con 0: 
[0 0 0 0 0 0 0 0 0 0]
Gener un arreglo con 1: 
[1 1 1 1 1 1 1 1 1 1]
Generar con arreglo con datos basura:
[5.e-324 5.e-324 5.e-324 5.e-324 5.e-324 5.e-324 5.e-324 5.e-324 5.e-324
 5.e-324]
Generar con arreglo con datos aleatorios, los primeros 2 numeros son el rango y el 3ro la longitud:
[44 89 32 32 35 41  8 90 87 89]
Obtener el valor del arreglo
4
Editar un elemento del arreglo
[100   2   3   4   5]
Cantidad de atributos que almacena
5
Obtiene la 

<ipython-input-2-db31b6f3d965>:12: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  c=np.array([1,2,3,4,5], dtype=np.complex)


2. Tambien podemos realizar operaciones matematicas con arreglos:

In [ ]:
print('Genera un nuevo arrelgo aplicando la operacion indicada: ')
print(a+10)
print(a-10)
print(a*10)
print(a/10)

print('Operaciones con otro arreglo:')
b = np.array([6,7,8,9,10])
print('Original: ',a)
print('Nuevo: ',b)

print('Resultado a + b:')
print(a+b)





Genera un nuevo arrelgo aplicando la operacion indicada: 
[110  12  13  14  15]
[90 -8 -7 -6 -5]
[1000   20   30   40   50]
[10.   0.2  0.3  0.4  0.5]
Operaciones con otro arreglo:
Original:  [100   2   3   4   5]
Nuevo:  [ 6  7  8  9 10]
Resultado a + b:
[106   9  11  13  15]


3. SubArreglos

In [ ]:
#a[start:end:saltos]

a = np.random.randint(0,100,10)
print('Arreglo: ', a)
print('Sub-arreglo obtenemos del indice 0 al 5: ', a[0:5])
print('Sub-arreglo  del indice 5 al final: ',a[5:])
print('Sub-arreglo del indice 5 al final con saltos de 2: ',a[5::2])

#caso especial donde necesitas generar un listado de indices
print('Sub-arreglo con indices espesificos: ',a[[0,1,3]])

#Podemos estraer info. a partir de un listado de elementos bolean
#debe tener el mismo tamaño del arreglo
print('Con boolean: ', a[[True,False,False,False,False,False,False,False,False,True]])

Arreglo:  [73 50 96 44 51 87 76 88 64 89]
Sub-arreglo obtenemos del indice 0 al 5:  [73 50 96 44 51]
Sub-arreglo  del indice 5 al final:  [87 76 88 64 89]
Sub-arreglo del indice 5 con saltos de 2:  [87 88 89]
Sub-arreglo con indices espesificos:  [73 50 44]
Con boolean:  [73 89]


**4. Vectorizar funciones.**

Permite realizar operaciones de una funcion sobre los elementos de un arreglo.

In [ ]:
a = np.random.randint(0,100,5)
print('Arreglo original: ',a)

#declaramos la funcion
def operacion(valor):
  return(valor **2)+2

#Si queremos aplicar la funcion a los elementos del arreglo seria mediante
print('Aplicamos la funcion a cada elemento de arreglo y retorna entero')
for x in a:
 print( operacion(x))


#vectorizamos la funcion
vector  = np.vectorize(operacion)

#aplicamos la funcion al arreglo
print('Aplicamos la funcion vectorizada y retorna un arreglo')
vector(a)

Arreglo original:  [19 96 86 91 19]
Aplicamos la operacion a cada elemento de arreglo
363
9218
7398
8283
363
Aplicamos la funcion vectorizada


array([ 363, 9218, 7398, 8283,  363])

*5. Copias y vistas.*

Copia: un objeto que se copia del arreglo original. No refleja cambios




Vista: una objeto que apunta al arreglo original y que se reflejan los cambios entre ambos

In [ ]:
a = np.random.randint(0,100,5)
b = a.copy()
print('Aplicamos una suma al original, no afecta a la copia pero si a la vista')
a=a+10
print('Arreglo original: ',a)
print('Arreglo copia:',b)

c = a.view()
print('Arreglo tipo vista: ', c)
print('Si modificas la vista tambien afecta al original pero no en la copia')
c[0]=10001
print('Vista',c)
print('Original',a)
print('Copia',b)


#Otra forma de generar vista
d = a[:]
#Saber a que apunta
d.base()
#o
d.base() is a





Aplicamos una suma al original, no afecta a la copia pero si a la vista
Arreglo original:  [54 47 37 48 55]
Arreglo copia: [44 37 27 38 45]
Arreglo tipo vista:  [54 47 37 48 55]
Si modificas la vista tambien afecta al original pero no en la copia
Vista [10001    47    37    48    55]
Original [10001    47    37    48    55]
Copia [44 37 27 38 45]


6. Matriz


In [ ]:
A = np.array([
    [1,2,3,4,5],
 [2,10,11,12,13],
  [3,4,5,2,5]
    ])
print(A)
print(type(A))
print(A.shape)

#las 2 formas de obetenr valores, lo común es hacerlo como la 2da forma
print('Valor del 1er elemento: ', A[0][0])
print('Valor del 2do elemento: ', A[0,1])


#Obtener sub-arreglos de la matriz
print('Sub-arreglo primer fila: ',A[0,:5])
print('Sub-arreglo de la 2da fila a partir del 11: ', A[1,2:])
print('Sub-arreglo 1er y ultimo elemento de la 1er fila: ',A[0,[0,4]])

print('Sub-arreglo de la 5ta columna: ',A[:,3])

[[ 1  2  3  4  5]
 [ 2 10 11 12 13]
 [ 3  4  5  2  5]]
<class 'numpy.ndarray'>
(3, 5)
Valor del 1er elemento:  1
Valor del 2do elemento:  2
Sub-arreglo primer fila:  [1 2 3 4 5]
Sub-arreglo de la 2da fila a partir del 11:  [11 12 13]
Sub-arreglo 1er y ultimo elemento de la 1er fila:  [1 5]
Sub-arreglo de la 5ta columna:  [ 4 12  2]


7. Metodos de agregacion.

Trabajamos con la matriz del ejercicio anterior.


In [ ]:
print('Matriz original',A)
#metodos
print('Obtenemos la desviacion estandar')
print(A.std())

print('La suma de sus elementos: ')
print(A.sum())

print('El valor minimo: ')
print(A.min())

print('El valor maximo: ')
print(A.max())

print('El valor promedio: ')
print(A.mean())

print('La suma de los elementos de la fila 1')
print(A[0].sum())

print('El valor maximo de la ultim fila: ')
print(A[2].max())





Matriz original [[ 1  2  3  4  5]
 [ 2 10 11 12 13]
 [ 3  4  5  2  5]]
Obtenemos la desviacion estandar
3.8620662287893968
La suma de sus elementos: 
82
El valor minimo: 
1
El valor maximo: 
13
El valor promedio: 
5.466666666666667
La suma de los elementos de la fila 1
15
El valor maximo de la ultim fila: 
5


In [ ]:
print('Matriz original: ',A)
print('Generamos una transposicion de la matriz ')
print(A.T)

Matriz original:  [[ 1  2  3  4  5]
 [ 2 10 11 12 13]
 [ 3  4  5  2  5]]
Generamos una transposicion de la matriz 
[[ 1  2  3]
 [ 2 10  4]
 [ 3 11  5]
 [ 4 12  2]
 [ 5 13  5]]


**8. Filtros y condiciones**



In [ ]:
#generamos un vector de prueba
a = np.random.randint(0,100,20)
print('Vector: ',a)

#operador condicional
print('Operador condicional')
print('\n', a>70)
print('\n', a[a>70])

#operador logico
print('Operador logico')
print('\n', a[(a>60)&(a<80)])
print('\n',a[(a==100)|(a==90)])

#condicion ALL y ANY
print('All: todos los elementos cumplen con las condiciones, regresa booleano\n')
print(np.all((a>10) & (a<15)))

print('\n Any: al menos 1 elemento cumple \n')
print(np.any((a>10) & (a<15)))




Vector:  [13 49 76 54 48 38 23 48 35 11 44 97 25 77 15 60 63 32 30 17]
Operador condicional

 [False False  True False False False False False False False False  True
 False  True False False False False False False]

 [76 97 77]
Operador logico

 [76 77 63]

 []
All: todos los elementos cumplen con las condiciones, regresa booleano

False

 Any: al menos 1 elemento cumple 

True


**8.1 Condicion Where y Select**

In [ ]:
notas = np.random.randint(0,11,10)
print('Calificaciones: \n',notas )

#Where: recibe 3 argumentos,
# 1er la condicion, 2do si cumple, 3ro en caso de no cumplir
#Select:admite 2 argumentos,
# 1ero un arreglo de condiciones, 2do un arreglo opciones
#Evalua la condicion y en caso de cumpli asirga la opcion que le corresponde


print('Funcion Where:\n',np.where(notas >= 7, 'Aprobado','Insuficiente' ))

print('\nFuncion select:\n',)
condicion=[(notas == 10), (notas>=7) & (notas<=9), (notas<=7) ]
opcion=(['Excelente 10'], ['Aprobaste'],['Insuficiente'])
print(np.select(condicion, opcion))




9. Crear y leer archivos del sistema.

Para trabajar con archivos en texto plarno es:
Guardar

np.savetxt('nombre.txt', arreglo, fmt='%i')

Leer

Debemos estar en la ruta del archivo:

np.loadtxt('nombre.txt', dtype=int)


En el caso de trabajar con matrices, la recomendacion es trabajar con el formato CSV.

np.savetxt('nombre.csv', matriz, delimiter=',', fmt='%i')

np.loadtxt('nombre.csv', delimiter=',', dtype=int)

Para trabajar con archivos en binario es:

Save - Load
 Por convencion se usa la extension .npy para archivos hechos con numpy.
np.save('nombre.py',arreglo)
np.load('nombre.py')



10. Modificar arreglos

Los arreglos no se pueden modificar en logitud lo que hacen los metodos es generar un nuevo arreglo con la modificacion que se solicita

In [ ]:
# insert o append
import numpy as np

a = np.random.randint(0,10,5)
print('Original',a)
print()
print('Otro con insert: ',np.insert(a,0,200))#arreglo,posicion,valor

a = np.append(a,144)#lo incorpora al final de arreglo
print('Con Append: ',a)


# Delete

print('Elimina el numero en posicion 0: ', np.delete(a,0))#arreglo, indice

#modificar el tamaño

print('Nuevo tamaño',np.resize(a,10))



#Unir distintos arreglos
 #np.concatenate([arreglo1, arreglo2])



Original [5 7 8 6 6]

Otro con insert:  [200   5   7   8   6   6]
Con Append:  [  5   7   8   6   6 144]
Elimina el numero en posicion 0:  [  7   8   6   6 144]
Nuevo tamaño [  5   7   8   6   6 144   5   7   8   6]


10. Ordenamiento


In [ ]:
#Metodo sort asc, aplica el cambio al mismo arreglo
a.sort()
print(a)
print(a[::-1])#nuevo arreglo y desc

#la funcion sort genero un nuevo arreglo con lo elemtos ordenados
np.sort(a)#asc
np.sort(a)[::-1] #desc

[  5   6   6   7   8 144]
[144   8   7   6   6   5]
